"""Pre-compute all views from results.db into a small JSON for the WASM app."""

import json
import sqlite3
import sys


def main():
    db_path = sys.argv[1] if len(sys.argv) > 1 else "data/results.db"
    out_path = sys.argv[2] if len(sys.argv) > 2 else "docs/data.json"

    conn = sqlite3.connect(db_path)

    r = conn.execute("SELECT MIN(block_num), MAX(block_num) FROM blocks").fetchone()
    n_blocks = conn.execute("SELECT COUNT(*) FROM blocks").fetchone()[0]
    n_txs = conn.execute("SELECT SUM(n_txs) FROM blocks").fetchone()[0] or 0
    n_storage = conn.execute("SELECT COUNT(*) FROM storage_ops").fetchone()[0]
    n_calls = conn.execute("SELECT COUNT(*) FROM calls").fetchone()[0]

    def query_dist(sql):
        return [[row[0], row[1]] for row in conn.execute(sql).fetchall()]

    data = {
        "meta": {
            "block_min": r[0], "block_max": r[1],
            "n_blocks": n_blocks, "n_txs": n_txs,
            "n_storage": n_storage, "n_calls": n_calls,
        },
        "distributions": {
            "ns_b": query_dist(
                "SELECT op_count AS n, COUNT(*) AS cnt FROM ("
                "  SELECT SUM(sload_count + sstore_count) AS op_count"
                "  FROM storage_ops GROUP BY block_num, address, slot"
                ") GROUP BY n ORDER BY n"
            ),
            "na_b": query_dist(
                "SELECT call_count AS n, COUNT(*) AS cnt FROM ("
                "  SELECT SUM(call_count) AS call_count"
                "  FROM calls GROUP BY block_num, address"
                ") GROUP BY n ORDER BY n"
            ),
            "ns_t": query_dist(
                "SELECT sload_count + sstore_count AS n, COUNT(*) AS cnt"
                " FROM storage_ops GROUP BY n ORDER BY n"
            ),
            "na_t": query_dist(
                "SELECT call_count AS n, COUNT(*) AS cnt"
                " FROM calls GROUP BY n ORDER BY n"
            ),
        },
        "extra_stats": {
            "max_slots_block": conn.execute(
                "SELECT MAX(cnt) FROM ("
                "  SELECT COUNT(DISTINCT address || '|' || slot) AS cnt"
                "  FROM storage_ops GROUP BY block_num)"
            ).fetchone()[0] or 0,
            "max_addrs_block": conn.execute(
                "SELECT MAX(cnt) FROM ("
                "  SELECT COUNT(DISTINCT address) AS cnt"
                "  FROM calls GROUP BY block_num)"
            ).fetchone()[0] or 0,
            "max_slots_tx": conn.execute(
                "SELECT MAX(cnt) FROM ("
                "  SELECT COUNT(DISTINCT address || '|' || slot) AS cnt"
                "  FROM storage_ops GROUP BY block_num, tx_idx)"
            ).fetchone()[0] or 0,
            "max_addrs_tx": conn.execute(
                "SELECT MAX(cnt) FROM ("
                "  SELECT COUNT(DISTINCT address) AS cnt"
                "  FROM calls GROUP BY block_num, tx_idx)"
            ).fetchone()[0] or 0,
        },
        "top_slots": [
            {"address": row[0], "slot": row[1], "sloads": row[2], "sstores": row[3], "total": row[4]}
            for row in conn.execute(
                "SELECT address, slot, SUM(sload_count), SUM(sstore_count), "
                "SUM(sload_count + sstore_count) AS total "
                "FROM storage_ops GROUP BY address, slot ORDER BY total DESC LIMIT 30"
            ).fetchall()
        ],
        "top_accounts": [
            {"address": row[0], "total_calls": row[1], "blocks_present": row[2]}
            for row in conn.execute(
                "SELECT address, SUM(call_count) AS total, COUNT(DISTINCT block_num) AS blocks "
                "FROM calls GROUP BY address ORDER BY total DESC LIMIT 30"
            ).fetchall()
        ],
        "per_block": [
            {"block": row[0], "txs": row[1], "unique_slots": row[2], "unique_addrs": row[3]}
            for row in conn.execute(
                "SELECT b.block_num, b.n_txs,"
                "  (SELECT COUNT(DISTINCT s.address || '|' || s.slot) FROM storage_ops s WHERE s.block_num = b.block_num),"
                "  (SELECT COUNT(DISTINCT c.address) FROM calls c WHERE c.block_num = b.block_num)"
                " FROM blocks b ORDER BY b.block_num"
            ).fetchall()
        ],
    }

    conn.close()

    # Write JSON
    with open(out_path, "w") as f:
        json.dump(data, f, separators=(",", ":"))

    # Also write as a Python module next to app.py (for WASM bundling)
    py_path = "data.py"
    with open(py_path, "w") as f:
        f.write("# Auto-generated by scripts/precompute.py — do not edit\n")
        f.write(f"DATA = {json.dumps(data, separators=(',', ':'))}\n")

    import os
    size_kb = os.path.getsize(out_path) / 1024
    print(f"Wrote {out_path} ({size_kb:.0f} KB)")
    print(f"Wrote {py_path} ({os.path.getsize(py_path) / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
